# Site Information
site_name: Sharppad Documentation
site_url: https://coretravis.github.io/sharppad/
repo_url: https://github.com/coretravis/sharppad
edit_uri: edit/main/docs/

# Theme Configuration (Material)
theme:
  name: material
  logo: assets/logo.png  # Add logo in docs/assets/
  favicon: assets/favicon.ico  # Add favicon in docs/assets/
  palette:
    - scheme: default  # Light Mode
      primary: blue
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate  # Dark Mode
      primary: blue
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs  # Adds a tabbed navigation bar
    - navigation.top  # Sticky navigation bar at the top
    - navigation.indexes  # Sub-index pages for sections
    - toc.integrate  # Table of contents inside the page
    - search.highlight  # Highlights search results
    - content.code.annotate  # Allows inline code annotations

# Navigation (Sidebar Structure)
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
  - Usage Guide: usage.md

# Markdown Extensions (For Better Formatting)
markdown_extensions:
  - toc:
      permalink: true  # Adds anchor links to headers
  - pymdownx.highlight  # Syntax highlighting for code blocks
  - pymdownx.superfences  # Nested code blocks
  - pymdownx.tabbed  # Tabbed content support
  - pymdownx.emoji  # Emoji support
  - pymdownx.tasklist  # Checkbox lists
  - pymdownx.snippets  # Allows reusing markdown snippets
  - pymdownx.inlinehilite  # Inline code highlighting

# Plugins (Additional Functionality)
plugins:
  - search  # Enables full-text search
  - tags  # Enables page tagging
#  - git-revision-date-localized  # Shows last modified date
docs_dir: docs